site_name: AI Learning Group
site_dir: site
docs_dir: docs/
theme:
  name: material

  palette:
    scheme: default #slate #> dark mode
    primary: indigo
    accent: blue

  features:
      # Keeps the table of contents visible while scrolling
      - toc.follow
      # Enables the "Back to top" button
      - content.action.top
      # Adds a copy button to code blocks (great motivation for users to try code!)
      - content.code.copy
      # Shows the hierarchy of the current page in the header
      - navigation.path
      # Expands all navigation sections by default
      #- navigation.expand

  font:
    text: Roboto
    code: Roboto Mono


markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
extra_css:
  - css/extra.css
plugins:
  - search

nav:
  - Home: README.md

  - Docs:

    - Community & Value:
      - A Chat GTP resposne: community-values-guidelines/Prompt-answer.md

    - AI:

      - AI - Fundamentals:
        - AI Fundamentals 1 : ai-sessions/fundamentals_of_LLM/README.md

      - AI Learning for Bigenners:
        - 2025 - Easy ways to Laern AI: ai-learning-plans/An-approach-to-learn-AI-in-2025-fueled-by-real-world-problem-solving-and-vigor.md
        - 2025 - AI Learning Path Draft: ai-learning-plans/ai-learning-plan-draft.md

      - AI Tools Hands-on:
        - Private Local & Free GuFF models: ai-tools-hands-on/AccessWorldOfFreeLLMs-guff/How-to-freely-access-use-LLMs-locally-securely-with-no-limits.md
        - Top Local LLMs: ai-tools-hands-on/CuratedLocalLLMs/Top-Local-LLMs.md 
      - AI Workflows:
        - n8n:
          - Prviate-Secure Docker-Desktop n8n + local LLM: ai-workflows/n8n/Local_N8N_setup_with_Local_AI/Step-by-step-guide-to-setup-n8n-locally-with-llm.md
          - Prviate-Secure Docker-Compose n8n + local LLM: ai-workflows/n8n/Local_N8N_setup_with_Local_AI/n8n-setup-with-docker-compose.md

      - AI-PC:
        - PC for Running 20b LLM: ai-pc/pc-for-running-20b-llm.md
        - CPU GPU for heavy LLMs: ai-pc/hardware-for-running-heavy-llms.md

    - Programming:
      - Python:
        - Easy Learning Sessions : easy-python-sessions/Sessions.md

